name: "Push"

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    name: Build 🛠️
    uses: ./.github/workflows/run_build.yml

  package:
    name: Package 📦
    uses: ./.github/workflows/run_package.yml
    needs:
      - build

  checks:
    name: Checks 📋
    uses: ./.github/workflows/run_checks.yml

  tests:
    name: Tests 🧪
    uses: ./.github/workflows/run_tests.yml
    needs:
      - build

  docs:
    name: Docs 📕
    uses: ./.github/workflows/run_docs.yml
